version: '3.8'

services:
  worker:
    build:
      context: ./worker
    ports:
      - "8000:8000"
    environment:
      # Force Hugging Face libraries to use a specific cache directory.
      - HF_HOME=/cache
    volumes:
      # Mount our local cache to the specified directory in the container.
      - ./model_cache:/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
