apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transcriber-gpu-worker
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/gpu-zonal-redundancy: "false"
        run.googleapis.com/minScale: "0"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      serviceAccountName: 811229424702-compute@developer.gserviceaccount.com
      containers:
      - image: europe-west4-docker.pkg.dev/whisper-flash-instance/transcriber-repo/transcriber:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: '4'
            memory: 16Gi
            nvidia.com/gpu: '1'
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
