# Use the runtime version of the PyTorch image to reduce size
# This image doesn't include development tools but still supports CUDA
FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies (ffmpeg is not in the base image)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Set up a working directory
WORKDIR /app

# Copy the requirements file and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


# Copy the application code
COPY main.py .

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run the application
# Use the PORT environment variable provided by Cloud Run
ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--log-level", "debug", "--port"]
CMD ["8080"]
